model_id: segment_anything_3_video
display_name: "Segment Anything 3 Video"
batch_processing_mode: "video"
auto_clear_cache_label_and_gid: true

params:
  bpe_path: "/workspace/x_anylabeling_server/models/bpe_simple_vocab_16e6.txt.gz"
  model_path: "/workspace/x_anylabeling_server/models/sam3.pt"
  devices: [0]
  conf_threshold: 0.25
  show_boxes: false
  show_masks: false
  show_rotations: true
  rotation_smooth: 0.6
  rotation_min_area: 10
  rotation_max_delta: 30
  epsilon_factor: 0.001

widgets:
  - name: button_add_point
    value: null
  - name: button_remove_point
    value: null
  - name: button_clear
    value: null
  - name: button_finish_object
    value: null
  - name: edit_text
    value: null
  - name: button_send
    value: null
  - name: input_conf
    value: null
  - name: edit_conf
    value: 0.25
  - name: mask_fineness_slider
    value: 10
  - name: mask_fineness_value_label
    value: null
  - name: toggle_preserve_existing_annotations
    value: false
