model_id: segment_anything_3_video
display_name: "Segment Anything 3 Video"
batch_processing_mode: "video"
auto_clear_cache_label_and_gid: true

params:
  bpe_path: "/workspace/x_anylabeling_server/models/bpe_simple_vocab_16e6.txt.gz"
  model_path: "/workspace/x_anylabeling_server/models/sam3.pt"
  devices: [0]
  conf_threshold: 0.25
  tracker_conf_threshold: 0.25
  tracker_drop_frames: 3
  tracker_drop_threshold: 0.25
  mask_min_area_ratio: 0.0
  mask_expand_ratio: 0.0
  mask_union_iou: 0.0
  mask_union_max_area_ratio: 0.0
  sam3_apply_temporal_disambiguation: true
  sam3_dynamic_multimask_stability_thresh: 0.98
  sam3_dynamic_multimask_stability_delta: 0.05
  sam3_mf_threshold: 0.01
  use_mask_bbox: true
  show_boxes: false
  show_masks: false
  show_rotations: true
  rotation_smooth: 0.6
  rotation_min_area: 10
  rotation_max_delta: 30
  rotation_lock_area_ratio: 1.2
  epsilon_factor: 0.001
  image_size: 1008
  session_frame_limit: 0
  propagate_chunk_size: 20
  offload_video_to_cpu: true
  offload_state_to_cpu: true
  async_loading_frames: true
  clear_cache_interval: 20
  max_sessions: 1
  video_loader_type: "cv2"

widgets:
  - name: button_add_point
    value: null
  - name: button_remove_point
    value: null
  - name: button_clear
    value: null
  - name: button_finish_object
    value: null
  - name: edit_text
    value: null
  - name: button_send
    value: null
  - name: image_size_label
    value: null
  - name: image_size_select_combobox
    value: 1008
  - name: session_frame_length_label
    value: null
  - name: session_frame_length_spinbox
    value: 0
  - name: input_conf
    value: null
  - name: edit_conf
    value: 0.25
  - name: mask_fineness_slider
    value: 10
  - name: mask_fineness_value_label
    value: null
  - name: toggle_preserve_existing_annotations
    value: false
